package app.vpncheck.core.provider

/** Fallback ASN -> (provider name, website) for common hosting companies. */
object AsnWebsiteTable {
    data class Entry(val name: String, val website: String)

    private val table: Map<Int, Entry> = mapOf(
        24940 to Entry("Hetzner Online", "https://www.hetzner.com"),
        213230 to Entry("Hetzner Cloud", "https://www.hetzner.com/cloud"),
        16276 to Entry("OVHcloud", "https://www.ovhcloud.com"),
        14061 to Entry("DigitalOcean", "https://www.digitalocean.com"),
        16509 to Entry("Amazon Web Services", "https://aws.amazon.com"),
        14618 to Entry("Amazon Web Services", "https://aws.amazon.com"),
        15169 to Entry("Google Cloud", "https://cloud.google.com"),
        396982 to Entry("Google Cloud", "https://cloud.google.com"),
        8075 to Entry("Microsoft Azure", "https://azure.microsoft.com"),
        13335 to Entry("Cloudflare", "https://www.cloudflare.com"),
        20473 to Entry("Vultr", "https://www.vultr.com"),
        63949 to Entry("Akamai / Linode", "https://www.linode.com"),
        9009 to Entry("M247", "https://www.m247.com"),
        51167 to Entry("Contabo", "https://contabo.com"),
        40021 to Entry("Contabo", "https://contabo.com"),
        141995 to Entry("Contabo", "https://contabo.com"),
        197540 to Entry("netcup", "https://www.netcup.de"),
        60068 to Entry("DataPacket (CDN77)", "https://www.datapacket.com"),
        212238 to Entry("DataPacket (CDN77)", "https://www.datapacket.com"),
        45102 to Entry("Alibaba Cloud", "https://www.alibabacloud.com"),
        37963 to Entry("Alibaba Cloud", "https://www.alibabacloud.com"),
        132203 to Entry("Tencent Cloud", "https://www.tencentcloud.com"),
        45090 to Entry("Tencent Cloud", "https://www.tencentcloud.com"),
        136907 to Entry("Huawei Cloud", "https://www.huaweicloud.com"),
        55990 to Entry("Huawei Cloud", "https://www.huaweicloud.com"),
        31898 to Entry("Oracle Cloud", "https://www.oracle.com/cloud/"),
        62240 to Entry("Clouvider", "https://www.clouvider.com"),
        44477 to Entry("Stark Industries Solutions", "https://stark-industries.solutions"),
        210644 to Entry("AEZA", "https://aeza.net"),
        401115 to Entry("AEZA", "https://aeza.net"),
        47583 to Entry("Hostinger", "https://www.hostinger.com"),
        202422 to Entry("Gcore", "https://gcore.com"),
        199524 to Entry("Gcore", "https://gcore.com"),
        39572 to Entry("Advanced Hosting", "https://advancedhosting.com"),
        61317 to Entry("Hivelocity", "https://www.hivelocity.net"),
        29802 to Entry("Hivelocity", "https://www.hivelocity.net"),
        8560 to Entry("IONOS", "https://www.ionos.com"),
        12876 to Entry("Scaleway", "https://www.scaleway.com"),
        49505 to Entry("Selectel", "https://selectel.ru"),
        50340 to Entry("Selectel", "https://selectel.ru"),
        200350 to Entry("Servers.com", "https://www.servers.com"),
        54825 to Entry("Equinix Metal", "https://deploy.equinix.com"),
        40676 to Entry("Psychz Networks", "https://www.psychz.net"),
        35916 to Entry("MULTACOM", "https://www.multacom.com"),
        174 to Entry("Cogent Communications", "https://www.cogentco.com"),
        3223 to Entry("Voxility", "https://www.voxility.com"),
        209605 to Entry("Host Baltic", "https://hostbaltic.com"),
        24961 to Entry("myLoc managed IT", "https://www.myloc.de"),
        212317 to Entry("HOSTKEY", "https://www.hostkey.com"),
        57043 to Entry("HOSTKEY", "https://www.hostkey.com"),
        44066 to Entry("First Colo", "https://www.first-colo.net"),
        48314 to Entry("IP-Projects", "https://www.ip-projects.de"),
        201814 to Entry("MEVSPACE", "https://mevspace.com"),
        42624 to Entry("DDoS-Guard", "https://ddos-guard.net"),
        396356 to Entry("Latitude.sh", "https://www.latitude.sh"),
        48282 to Entry("VDSina", "https://vdsina.ru"),
        39378 to Entry("servinga", "https://www.servinga.com"),
        60781 to Entry("Leaseweb", "https://www.leaseweb.com"),
        16265 to Entry("Leaseweb", "https://www.leaseweb.com"),
        28753 to Entry("Leaseweb", "https://www.leaseweb.com"),
        7203 to Entry("Leaseweb", "https://www.leaseweb.com"),
        60404 to Entry("Liteserver", "https://www.liteserver.nl"),
        43350 to Entry("NFOrce Entertainment", "https://www.nforce.com"),
        49981 to Entry("WorldStream", "https://www.worldstream.com"),
        47447 to Entry("23M", "https://www.23m.com"),
        51396 to Entry("Pfcloud", "https://pfcloud.io"),
        200019 to Entry("AlexHost", "https://alexhost.com"),
        199785 to Entry("Trabia", "https://www.trabia.net"),
        200593 to Entry("Cherry Servers", "https://www.cherryservers.com"),
        16125 to Entry("Cherry Servers", "https://www.cherryservers.com"),
        3214 to Entry("xTom", "https://xtom.com"),
        26548 to Entry("PureVoltage", "https://purevoltage.com"),
        23470 to Entry("ReliableSite", "https://www.reliablesite.net"),
        46844 to Entry("Sharktech", "https://www.sharktech.net"),
        33387 to Entry("Nocix / DataShack", "https://www.nocix.net"),
        36352 to Entry("ColoCrossing", "https://www.colocrossing.com"),
        63023 to Entry("GTHost", "https://gthost.com"),
        19318 to Entry("InterServer", "https://www.interserver.net"),
        11878 to Entry("tzulo", "https://www.tzulo.com"),
        53667 to Entry("FranTech / BuyVM", "https://buyvm.net"),
        8100 to Entry("QuadraNet", "https://www.quadranet.com"),
        20278 to Entry("Nexeon Technologies", "https://www.nexeon.com"),
        35913 to Entry("DediPath", "https://dedipath.com"),
        30823 to Entry("combahton", "https://combahton.net"),
        59711 to Entry("HZ Hosting", "https://www.hz.net"),
        25369 to Entry("Hydra Communications", "https://www.hydracom.net"),
        34665 to Entry("Petersburg Internet Network", "https://pinspb.ru"),
        41378 to Entry("Kirino", "https://kirino.ru"),
        210558 to Entry("1337 Services", "https://1337.services"),
        62005 to Entry("BlueVPS", "https://bluevps.com"),
        216071 to Entry("Servers Tech Fzco", "https://servers.tech"),
        215540 to Entry("Global Connectivity Solutions", "https://gcs.ae"),
        204601 to Entry("Timeweb", "https://timeweb.cloud"),
        9123 to Entry("Timeweb", "https://timeweb.cloud"),
        61400 to Entry("Timeweb", "https://timeweb.cloud"),
        210079 to Entry("Timeweb", "https://timeweb.cloud"),
        35540 to Entry("Timeweb", "https://timeweb.cloud"),
        203584 to Entry("Timeweb", "https://timeweb.cloud"),
        49392 to Entry("Timeweb (Baxet)", "https://timeweb.cloud"),
        57523 to Entry("Chang Way Technologies", "https://changway.hk"),
        202306 to Entry("Hostglobal.plus", "https://hostglobal.plus"),
        204957 to Entry("Green Floid", "https://greenfloid.com"),
        207713 to Entry("Global Internet Solutions", "https://gir.network"),
        197695 to Entry("Reg.ru", "https://www.reg.ru"),
        197226 to Entry("SPRINT SDC", "https://sprinthost.ru"),
        50113 to Entry("Melbicom", "https://melbicom.net"),
        56630 to Entry("Melbicom", "https://melbicom.net"),
        204603 to Entry("Melbicom", "https://melbicom.net"),
        59642 to Entry("UK-2 Limited", "https://www.uk2.net"),
        202425 to Entry("IP Volume", "https://ipvolume.net"),
        29182 to Entry("JSC IOT (ISPsystem)", "https://ispserver.com"),
        200557 to Entry("Kamatera", "https://www.kamatera.com"),
        210906 to Entry("MIRholding", "https://mirholding.nl"),
        398324 to Entry("Censys", "https://censys.io"),
        135377 to Entry("UCloud", "https://www.ucloud-global.com"),
        152194 to Entry("ChinaNet Cloud", "https://www.ctyun.cn"),
        4837 to Entry("China Unicom", "https://www.chinaunicom.com"),
        4134 to Entry("China Telecom", "https://www.chinatelecom-h.com"),
        58224 to Entry("Iran Telecommunication Company", "https://tci.ir"),
        44244 to Entry("Iran Cell", "https://irancell.ir"),
        197207 to Entry("MCI (Hamrah Aval)", "https://mci.ir"),
        16322 to Entry("ParsOnline", "https://parsonline.com"),
        59441 to Entry("Arvan Cloud", "https://www.arvancloud.ir"),
        202468 to Entry("Arvan Cloud", "https://www.arvancloud.ir"),
        49666 to Entry("Iran Telecommunication Research Center", "https://itrc.ac.ir"),
        43754 to Entry("Asiatech", "https://asiatech.ir"),
        31549 to Entry("Aria Shatel", "https://shatel.ir"),
        213365 to Entry("Fanap Telecom", "https://fanaptelecom.ir"),
        202059 to Entry("Hetzner (legacy)", "https://www.hetzner.com"),
    )

    fun lookup(asn: Int?): Entry? = asn?.let { table[it] }
}
